import type { Clave } from './es';

/** English. Same keys as es.ts: a missing one does not compile. */
export const en: Record<Clave, string> = {
  'comun.pasoDe': '{paso} of {total}',
  'decision.respondido': 'Answered',
  'decision.dijisteSi':
    "You said yes. At 22:00 you'll find out whether they wanted to keep going too.",
  'decision.dijisteNo': "You said no. They won't know what you answered.",
  'decision.cambiarIdea': 'You can change your mind until 22:00.',
  'decision.ultimosMinutos': '⏳ Last few minutes',
  'decision.pregunta': 'Do you want to keep getting to know this person?',
  'decision.anonimo':
    "You each answer on your own. If you don't match, nobody knows what the other said.",
  'decision.si': 'Yes, keep going 💖',
  'decision.no': "I'll leave it here",
  'reportar.respeto': "They're being disrespectful",
  'reportar.sexual': "Sexual content I didn't ask for",
  'reportar.spam': "Spam, or they're selling something",
  'reportar.falso': "They don't seem to be who they say",
  'reportar.menor': 'They look under 18',
  'reportar.otra': 'Something else',
  'comun.noSePudoEnviar': "Couldn't send it.",
  'reportar.etiqueta': 'Report or block',
  'reportar.titulo': 'What happened?',
  'reportar.ayuda':
    "The conversation ends right now and we'll never match you again. They won't know it was you.",
  'reportar.soloBloquear': 'Just block, no reason',
  'comun.cancelar': 'Cancel',
  'presentacion.titulo': 'Your conversation\nstarts now!',
  'presentacion.detalle': '{detalle}. The rest you find out by talking.',
  'presentacion.toca': 'Tap to start',
  'nivel.0.titulo': 'Match',
  'nivel.0.desc': 'Age, two interests, area',
  'nivel.1.titulo': 'First message',
  'nivel.1.desc': 'Nickname and all interests',
  'nivel.2.titulo': 'Conversation',
  'nivel.2.desc': 'Their three questions',
  'nivel.3.titulo': 'Good connection',
  'nivel.3.desc': 'Photo, if you both agree',
  'nivel.4.titulo': 'Trust',
  'nivel.4.desc': 'Whatever each of you wants',
  'comun.anos': '{edad} years old',
  'comun.aUnosKm': 'about {km} km away',
  'comun.nivelTitulo': 'Level {nivel} · {titulo}',
  'perfilOtro.siguiente': 'Next: {titulo} · {desc}',
  'perfilOtro.intereses': 'Their interests',
  'perfilOtro.enComun': 'In purple, the ones you share',
  'perfilOtro.preguntas': 'Their questions',
  'perfilOtro.preguntasBloqueadas': '🔒 Their three questions arrive at level 2',
  'perfilOtro.mas': 'More about them',
  'perfilOtro.habla': 'Speaks {idiomas}',
  'perfilOtro.masBloqueado': '🔒 Photo and the rest of the profile, at level 3',
  'foto.pedido': "Asked. The photo will appear if they ask too, and they won't know you did.",
  'foto.titulo': 'Want to see each other?',
  'foto.ayuda': 'You both have to ask. Nobody knows whether the other one did.',
  'foto.quieroVerte': 'I want to see you',
  'dia.titulo': 'Your day',
  'dia.reparto': 'Match ✓',
  'dia.decision': 'Decision',
  'dia.cierre': 'Closes',
  'dia.cerrado': "🌙 Today's closed. New match tomorrow at 4:00.",
  'dia.decidiendo':
    "⏳ It's the last half hour: go to the chat and say whether you want to keep going.",
  'dia.preguntaremos': "At {hora} we'll ask whether you want to keep getting to know this person.",
  'conexiones.titulo': 'Your connections 💖',
  'conexiones.vacio':
    "If you both say yes at the end of the day, they'll show up here. Connections never expire.",
  'conexiones.nota': "Connections never expire and don't take up your conversation of the day.",
  'consejo.0': "Ask about one of their interests: it's the best way to get a conversation going.",
  'consejo.1': 'Open questions go further than yes-or-no ones.',
  'consejo.2':
    "No rush for the photo: the more you talk first, the more you'll want to see each other.",
  'consejo.3': 'Saying no at the end of the day is anonymous: nobody will know what you answered.',
  'consejo.4':
    "Reply to what they tell you before changing the subject: it shows you're listening.",
  'consejo.5': 'Humour helps, but what really hooks people is genuine curiosity.',
  'consejo.6': "If it's not flowing, ask about their perfect Tuesday.",
  'consejo.7': 'Your three questions are read at level 2: give them something to reply to.',
  'consejo.8': 'A long message now and then says more than ten one-word ones.',
  'consejo.9': 'If someone makes you uncomfortable, reporting ends the conversation instantly.',
  'chat.errorAbrir': "Couldn't open the conversation.",
  'chat.errorCorazon': "Couldn't send the heart.",
  'chat.errorPedir': "Couldn't ask.",
  'chat.errorResponder': "Couldn't answer.",
  'comun.volver': '‹ Back',
  'chat.verPerfil': 'See profile ›',
  'chat.conexion': '💖 Connection',
  'chat.reportar': 'Report',
  'chat.hielo': 'To break the ice',
  'chat.pistaCorazon': 'Double-tap one of their messages to give it a ❤️',
  'chat.cortada': "This conversation has been cut off. We won't match you again.",
  'chat.cerrada': 'This conversation closed at 22:00. New match tomorrow at 4:00.',
  'chat.escribe': 'Write something…',
  'comun.edadYDistancia': '{edad} · {km} km away',
  'comun.sinServidor': "Couldn't reach the server.",
  'hoy.miPerfil': 'My profile',
  'hoy.titular': "Today you're talking to…",
  'hoy.etiqueta': 'LEVEL 0 · MATCH',
  'hoy.quedan': '⏳ {tiempo} left',
  'hoy.distancia': 'about {km} km away · no photo or nickname yet',
  'hoy.unoEnComun': 'One interest in common with you',
  'hoy.variosEnComun': '{n} interests in common with you',
  'hoy.seguir': 'Keep talking',
  'hoy.empezar': 'Tap to start talking',
  'buscando.titulo': "Today's match",
  'buscando.cuerpo':
    "It happens on its own, once a day, always at the same time. You don't pick: we look for what suits you both.",
  'buscando.cuando': 'When',
  'buscando.pronto': 'Soon',
  'buscando.ampliamos':
    "If you've gone a few days without a match, we widen the search little by little and let you know.",
  'genero.WOMAN': 'Woman',
  'genero.MAN': 'Man',
  'genero.NON_BINARY': 'Non-binary',
  'genero.OTHER': 'Other',
  'busca.WOMAN': 'Women',
  'busca.MAN': 'Men',
  'busca.NON_BINARY': 'Non-binary people',
  'busca.OTHER': 'Other genders',
  'intencion.FRIENDSHIP': 'Friendship',
  'intencion.DATING': 'Dating',
  'intencion.RELATIONSHIP': 'Relationship',
  'intencion.CASUAL': 'Something casual',
  'sociabilidad.1': 'Slow to warm up',
  'sociabilidad.2': 'On the quiet side',
  'sociabilidad.3': 'Depends on the day',
  'sociabilidad.4': 'Pretty sociable',
  'sociabilidad.5': "I'll talk to anyone",
  'perfil.borrarSiempre': 'Delete forever',
  'perfil.borrarTitulo': 'Delete your account?',
  'perfil.borrarAviso':
    "Everything goes: your profile, your photo, your conversations and your connections. They also disappear for the people you talked to. This can't be undone.",
  'perfil.noSeBorro': "Couldn't delete it",
  'comun.reintentar': 'Try again in a moment.',
  'perfil.edad': 'Age',
  'perfil.genero': 'Gender',
  'perfil.hablarCon': 'You want to talk to',
  'perfil.todos': 'Everyone',
  'perfil.edades': 'Ages',
  'perfil.rangoEdad': '{min} – {max}',
  'perfil.distancia': 'Distance',
  'perfil.hastaKm': 'Up to {km} km',
  'perfil.buscas': 'Looking for',
  'perfil.conversacion': 'Conversation',
  'perfil.relacionas': 'How you connect',
  'perfil.editar': '✏️ Edit',
  'perfil.basico': 'The basics',
  'perfil.idiomas': '🗣️ Languages',
  'perfil.intereses': 'Your interests',
  'perfil.preguntas': 'Your three questions',
  'perfil.masDeTi': 'A bit more about you',
  'perfil.dedicas': '💼 What you do',
  'perfil.deDonde': "🏡 Where you're from",
  'perfil.ajustes': 'Settings',
  'perfil.cambiarRespuestas': 'Change my answers',
  'perfil.cerrarSesion': 'Log out',
  'perfil.borrando': 'Deleting…',
  'perfil.borrar': 'Delete my account',
  'comoTeVen.titulo': 'How others see you',
  'comoTeVen.pista': 'Tap a level to see what they find out about you there.',
  'comoTeVen.nivel0': '{edad} years old, a few km away. Not your name, not your photo.',
  'comoTeVen.dosIntereses': 'Just two of your interests, the ones you have most in common.',
  'comoTeVen.nivel1': 'Your nickname, “{apodo}”, and all your interests:',
  'comoTeVen.foto': 'Your photo, if you both ask',
  'comoTeVen.nivel4':
    '💖 Whatever each of you wants to share. It comes if you both say yes at the end of the day, and it never expires.',
  'comoTeVen.siguiente': '🔒 Next: {desc}',
  'intro.saltar': 'Skip',
  'intro.1.titulo': 'Talk first. Look later.',
  'intro.1.frase': "The photo doesn't come first: it clears up as the conversation goes well.",
  'intro.2.titulo': 'One person a day.',
  'intro.2.frase': 'Every morning you get someone, and you have until 22:00 to talk.',
  'intro.3.titulo': 'It unlocks as you talk.',
  'intro.3.frase':
    'The more you talk, the more you get to know each other. And the photo, only if you both want.',
  'intro.4.titulo': 'At the end, you both decide.',
  'intro.4.frase': "If you both say yes, it's a connection, and it never expires.",
  'intro.crearCuenta': 'Create my account',
  'intro.siguiente': 'Next',
  'intro.yaTengo': 'I already have an account',
  'intro.chat1': 'Mountains or climbing gym?',
  'intro.chat2': 'Mountains, always 🏔️',
  'intro.chat3': 'Finally, someone with taste!',
  'intro.duranteElDia': 'During the day',
  'intro.momento1': 'Your person of the day arrives',
  'intro.momento2': 'You talk at your own pace',
  'intro.momento3': 'The conversation closes',
  'intro.peldano0': 'Age and two interests',
  'intro.peldano1': 'Their nickname, once you both write',
  'intro.peldano2': 'Their three questions',
  'intro.peldano3': 'Their photo, if you both want',
  'intro.peldano4': 'Whatever you want to share',
  'intro.si': 'Yes?',
  'login.email': 'Your email',
  'login.emailAyuda': "We'll send you a six-digit code. No passwords to remember or lose.",
  'login.emailEjemplo': 'you@email.com',
  'login.enviarCodigo': 'Send me the code',
  'login.codigo': 'The code we sent you',
  'login.codigoAyuda': 'To {email}. It expires in ten minutes.',
  'login.entrar': 'Log in',
  'login.otroCodigo': 'Change email or get another code',
  'login.lema': 'Talk first, look later',
  'comun.sinConexion': "Couldn't connect to the server.",
  'bloque.quien': 'Who you are',
  'bloque.busca': "Who you're looking for",
  'bloque.donde': 'Where and in which language',
  'bloque.hablas': 'How you talk',
  'bloque.cuentas': 'What you share about yourself',
  'bloque.foto': 'Your photo',
  'registro.fotoFallo': "Your profile is saved, but the photo didn't upload: {motivo}",
  'registro.error': "Couldn't save your profile.",
  'registro.terminar': 'Finish sign-up',
  'registro.continuar': 'Continue',
  'editar.fotoFallo': "Your changes are saved, but the photo didn't upload: {motivo}",
  'editar.error': "Couldn't save the changes.",
  'editar.ayuda':
    'Only touch what you want to change. Everything saves together with the button below.',
  'editar.guardar': 'Save changes',
  'intencion.FRIENDSHIP.pista': 'People to talk to',
  'intencion.DATING.pista': 'Getting to know someone, no rush',
  'intencion.RELATIONSHIP.pista': 'Something that lasts',
  'intencion.CASUAL.pista': 'No plans for the future',
  'idioma.es': 'Spanish',
  'idioma.en': 'English',
  'idioma.ca': 'Catalan',
  'idioma.gl': 'Galician',
  'idioma.eu': 'Basque',
  'idioma.fr': 'French',
  'idioma.pt': 'Portuguese',
  'idioma.it': 'Italian',
  'idioma.de': 'German',
  'idioma.ar': 'Arabic',
  'idioma.ro': 'Romanian',
  'idioma.nl': 'Dutch',
  'idioma.pl': 'Polish',
  'idioma.ru': 'Russian',
  'idioma.uk': 'Ukrainian',
  'idioma.zh': 'Chinese',
  'idioma.ja': 'Japanese',
  'idioma.ko': 'Korean',
  'idioma.hi': 'Hindi',
  'idioma.ur': 'Urdu',
  'idioma.bn': 'Bengali',
  'idioma.tr': 'Turkish',
  'idioma.el': 'Greek',
  'idioma.sv': 'Swedish',
  'idioma.no': 'Norwegian',
  'idioma.da': 'Danish',
  'idioma.fi': 'Finnish',
  'idioma.cs': 'Czech',
  'idioma.hu': 'Hungarian',
  'idioma.he': 'Hebrew',
  'nivelIdioma.BASIC': 'I get by… barely',
  'nivelIdioma.INTERMEDIATE': 'I can hold my own',
  'nivelIdioma.NATIVE': 'Like at home',
  'generoDetalle.0': 'Woman',
  'generoDetalle.1': 'Man',
  'generoDetalle.2': 'Trans woman',
  'generoDetalle.3': 'Trans man',
  'generoDetalle.4': 'Non-binary',
  'generoDetalle.5': 'Genderfluid',
  'generoDetalle.6': 'Agender',
  'generoDetalle.7': 'Bigender',
  'generoDetalle.8': 'Queer',
  'generoDetalle.9': 'Intergender',
  'generoDetalle.10': 'Questioning',
  'generoDetalle.11': 'Prefer not to say',
  'pregunta.last-hooked.ejemplo': 'E.g. a documentary about octopuses, I watched it twice',
  'pregunta.always-ask.ejemplo': "E.g. what's your ideal breakfast?",
  'pregunta.weird-habit.ejemplo': 'E.g. I name all my plants',
  'pregunta.makes-me-laugh.ejemplo': 'E.g. videos of cats falling off things',
  'pregunta.perfect-tuesday.ejemplo': 'E.g. coffee, a walk by the sea and a series',
  'pregunta.learned-late.ejemplo': 'E.g. swimming, at 25',
  'pregunta.hill-to-die-on.ejemplo': 'E.g. Spanish omelette, with onion',
  'pregunta.surprisingly-good-at.ejemplo': 'E.g. parking on the first try',
  'pregunta.always-return.ejemplo': 'E.g. a bar in my neighbourhood with the best patatas bravas',
  'pregunta.changed-my-mind.ejemplo': 'E.g. I used to hate running',
  'pregunta.too-much-internet.ejemplo': 'E.g. ten-second videos',
  'pregunta.want-to-try.ejemplo': 'E.g. finally trying surfing',
  'pregunta.worst-recommendation.ejemplo': 'E.g. a film nobody made it to the end of',
  'pregunta.gives-me-away.ejemplo': 'E.g. my laugh, you can hear it from across the room',
  'pregunta.not-in-my-interests.ejemplo': 'E.g. I collect old postcards',
  'apodo.titulo': 'What do you want to be called?',
  'apodo.ayuda':
    "It shows up at level 1, as soon as you've both written. Your real name isn't needed.",
  'apodo.placeholder': 'Your nickname',
  'nacimiento.titulo': 'Your date of birth',
  'nacimiento.ayuda': "18+ only. Before the beta we'll verify age properly, not with a checkbox.",
  'genero.titulo': 'Your gender',
  'genero.ayuda':
    'Matching works from these four, and that’s why there are four. At level 0 only your age, two interests and your area are shown.',
  'generoDetalle.titulo': 'And how do you put it?',
  'generoDetalle.ayuda':
    "Optional. This is read at level 3 and isn't used for matching, so you can be as precise as you like.",
  'generoDetalle.placeholder': 'Or write it your own way',
  'busco.titulo': 'Who do you want to talk to?',
  'busco.ayuda': 'You can pick several. We only match when it works both ways.',
  'busco.todosDetalle': 'Selects all four above',
  'rango.titulo': 'Age and distance',
  'rango.ayuda':
    "If you've been waiting a few days, we widen this little by little and let you know.",
  'ubicacion.titulo': 'Where are you?',
  'ubicacion.ayuda':
    "We ask once and store it rounded to over a kilometre. We don't track where you go.",
  'ubicacion.usar': 'Use my location',
  'idiomas.titulo': 'Which languages do you speak?',
  'idiomas.ayuda':
    "Everything here happens in writing, so you need a language in common. Say how well you speak it too: if you mark it as weak, we won't pair you with someone you only share that language with.",
  'rasgos.ayuda': 'No right or wrong answers: it helps us avoid pairing rhythms that clash.',
  'conversacion.titulo': 'What kind of conversation do you like?',
  'conversacion.ayuda': 'This is where the question that opens your first chat comes from.',
  'intencion.titulo': 'What are you looking for right now?',
  'intencion.ayuda': 'Pick what matters most today. You can change it whenever you like.',
  'intereses.buscar': 'Search',
  'preguntas.ayuda':
    "Pick three and finish the sentence. It's what the other person reads at level 2, and it gives them something to reply to.",
  'masDeTi.dedicasEjemplo': 'E.g. nurse, I study design…',
  'masDeTi.deDondeEjemplo': 'E.g. Girona, though I live in Barcelona',
  'fotoPropia.titulo': 'A photo of you',
  'rango.edad': '🎂 Their age',
  'rango.distancia': '📍 Distance',
  'ubicacion.tomada': 'Location saved',
  'intereses.tuyos': 'Yours',
  'intereses.nada': 'Nothing by that name.',
  'preguntas.cambiar': 'Change ›',
  'preguntas.verMuestra': '👀 How the other person will see it',
  'preguntas.elige': 'Pick a question',
  'preguntas.sorpresa': '🎲 Surprise me',
  'preguntas.enSuPantalla': 'On their screen, at level 2',
  'masDeTi.opcional': 'Optional',
  'masDeTi.nivel3': '🔒 Visible from level 3',
  'fotoPropia.tocar': 'Tap to choose',
  'fotoPropia.otra': 'Choose another',
  'fotoPropia.queHacemos': 'What we do with it',
  'nacimiento.vacio': 'Tap the boxes and type day, month and year',
  'nacimiento.noExiste': "That date doesn't exist, check it",
  'nacimiento.menor': 'Olimpus is for over-18s only',
  'nacimiento.tienes': "You're {edad}",
  'rango.deA': 'From {min} to {max}',
  'ubicacion.sinPermiso':
    "Without your location we can't work out distance. You can allow it in Settings.",
  'ubicacion.sinGps': "Couldn't read your location. Check that GPS is on.",
  'ubicacion.error': "Couldn't read your location.",
  'ubicacion.nota': "Saved with low precision on purpose: it's for distance, not for finding you.",
  'intereses.titulo': 'Between {min} and {max} interests',
  'pregunta.ejemploGenerico': 'Finish the sentence your way',
  'fotoPropia.errorGaleria': "Couldn't open your photos.",
  'fotoPropia.nota':
    "It's shrunk on your phone before sending, and rewriting it strips the hidden data photos carry, including where it was taken. There's no public link on the server: every time someone asks for it, we check whether they're allowed to see it.",
  'rango.barrio': '🏘️ Your neighbourhood and around',
  'rango.ciudad': '🏙️ Your city',
  'rango.zona': '🚗 Your area, a short drive away',
  'rango.provincia': '🗺️ Your whole region and beyond',
  'ubicacion.tomando': 'Getting it…',
  'ubicacion.otraVez': 'Get it again',
  'intereses.llevas': "{n} so far. This is where each conversation's first question comes from.",
  'intereses.elegidos': '{n} chosen. The rarer, the more it says about you.',
  'preguntas.hueco0': 'Pick your first question',
  'preguntas.hueco1': 'Pick your second question',
  'preguntas.hueco2': 'Pick your third question',
  'fotoPropia.yaTienes': 'You already have one saved. Only tap it if you want to change it.',
  'fotoPropia.ayuda':
    "Nobody sees it when matching. It shows up at level 3, and only if you've both said you want to see each other.",
  'rasgo.titulo.largo': 'When writing',
  'rasgo.titulo.ritmo': 'My pace',
  'rasgo.titulo.rol': 'In a chat',
  'rasgo.largos': 'Long messages',
  'rasgo.depende': 'Depends',
  'rasgo.cortos': 'Short and frequent',
  'rasgo.cuandoPuedo': 'When I can',
  'rasgo.alMomento': 'I reply right away',
  'rasgo.escucho': 'I listen more',
  'rasgo.pregunto': 'I ask a lot',
  'conversacion.A fondo': 'Deep',
  'conversacion.Ligera y con humor': 'Light and funny',
  'conversacion.Curiosa': 'Curious',
  'conversacion.Práctica': 'Practical',
  'conversacion.pista.A fondo': 'Few topics, done well',
  'conversacion.pista.Ligera y con humor': 'Nothing too intense',
  'conversacion.pista.Curiosa': 'Odd questions, what-ifs',
  'conversacion.pista.Práctica': 'Plans, the city, things to do',
  'comun.servidorRespondio': 'The server replied {estado}',
  'fotoPropia.errorSubir': "Couldn't upload the photo.",
  'fotoPropia.sinPermiso':
    "Without permission we can't open your photos. You can allow it in Settings.",
  'idiomaApp.titulo': 'App language',
  'idiomaApp.ayuda': 'Messages and profiles from other people stay as they wrote them.',
  'rango.zonaNota': 'Your location is never shown exactly: the other person sees “3 km away”.',
  'masDeTi.nota': "They aren't used for matching: they just help people get to know you.",
  'subida.titulo': 'Level {nivel}!',
  'subida.desbloqueado': 'Now you can see: {desc}',
};
