/**
 * Castellano: el idioma de referencia. Cada clave de aquí tiene que estar en los
 * demás diccionarios (lo comprueba TypeScript). Las {llaves} son variables.
 */
export const es = {
  'comun.pasoDe': '{paso} de {total}',
  'decision.respondido': 'Respondido',
  'decision.dijisteSi':
    'Has dicho que sí. A las 22:00 sabrás si la otra persona también quiso seguir.',
  'decision.dijisteNo': 'Has dicho que no. La otra persona no sabrá qué respondiste.',
  'decision.cambiarIdea': 'Puedes cambiar de idea hasta las 22:00.',
  'decision.ultimosMinutos': '⏳ Últimos minutos',
  'decision.pregunta': '¿Quieres seguir conociendo a esta persona?',
  'decision.anonimo':
    'Cada uno responde por su cuenta. Si no coincidís, nadie sabe qué respondió el otro.',
  'decision.si': 'Sí, seguir 💖',
  'decision.no': 'Aquí lo dejo',
  'reportar.respeto': 'Me falta al respeto',
  'reportar.sexual': 'Contenido sexual que no he pedido',
  'reportar.spam': 'Spam o me quiere vender algo',
  'reportar.falso': 'No parece quien dice ser',
  'reportar.menor': 'Parece menor de edad',
  'reportar.otra': 'Otra cosa',
  'comun.noSePudoEnviar': 'No se pudo enviar.',
  'reportar.etiqueta': 'Reportar o bloquear',
  'reportar.titulo': '¿Qué ha pasado?',
  'reportar.ayuda':
    'La conversación se corta ahora mismo y no os volveremos a emparejar. La otra persona no sabrá que has sido tú.',
  'reportar.soloBloquear': 'Solo bloquear, sin motivo',
  'comun.cancelar': 'Cancelar',
  'presentacion.titulo': '¡Empieza vuestra\nconversación!',
  'presentacion.detalle': '{detalle}. El resto se descubre hablando.',
  'presentacion.toca': 'Toca para empezar',
  'nivel.0.titulo': 'Match',
  'nivel.0.desc': 'Edad, dos intereses, zona',
  'nivel.1.titulo': 'Primer mensaje',
  'nivel.1.desc': 'Apodo y todos los intereses',
  'nivel.2.titulo': 'Conversación',
  'nivel.2.desc': 'Sus tres preguntas',
  'nivel.3.titulo': 'Buena conexión',
  'nivel.3.desc': 'Foto, si los dos aceptáis',
  'nivel.4.titulo': 'Confianza',
  'nivel.4.desc': 'Lo que cada uno quiera',
  'comun.anos': '{edad} años',
  'comun.aUnosKm': 'a unos {km} km',
  'comun.nivelTitulo': 'Nivel {nivel} · {titulo}',
  'perfilOtro.siguiente': 'Siguiente: {titulo} · {desc}',
  'perfilOtro.intereses': 'Sus intereses',
  'perfilOtro.enComun': 'En morado, los que tenéis en común',
  'perfilOtro.preguntas': 'Sus preguntas',
  'perfilOtro.preguntasBloqueadas': '🔒 Sus tres preguntas llegan en el nivel 2',
  'perfilOtro.mas': 'Más de su perfil',
  'perfilOtro.habla': 'Habla {idiomas}',
  'perfilOtro.masBloqueado': '🔒 Foto y resto del perfil, en el nivel 3',
  'foto.pedido':
    'Pedido. La foto aparecerá si la otra persona también lo pide, y no sabrá que tú lo hiciste.',
  'foto.titulo': '¿Queréis veros?',
  'foto.ayuda': 'Hace falta que lo pidáis los dos. Nadie sabe si el otro lo pidió.',
  'foto.quieroVerte': 'Quiero verte',
  'dia.titulo': 'Tu día',
  'dia.reparto': 'Reparto ✓',
  'dia.decision': 'Decisión',
  'dia.cierre': 'Cierre',
  'dia.cerrado': '🌙 El día ya ha cerrado. Mañana a las 4:00 hay reparto nuevo.',
  'dia.decidiendo': '⏳ Es la última media hora: entra al chat y di si quieres seguir.',
  'dia.preguntaremos': 'A las {hora} te preguntaremos si quieres seguir conociendo a esta persona.',
  'conexiones.titulo': 'Tus conexiones 💖',
  'conexiones.vacio':
    'Si al final del día los dos decís que sí, aparecerá aquí. Las conexiones no caducan.',
  'conexiones.nota': 'Las conexiones no caducan ni ocupan tu conversación del día.',
  'consejo.0': 'Pregunta por algo de sus intereses: es lo que mejor arranca una conversación.',
  'consejo.1': 'Las preguntas abiertas dan más juego que las de sí o no.',
  'consejo.2': 'No hay prisa por la foto: cuanto más habléis antes, más os apetecerá veros.',
  'consejo.3': 'Decir que no al final del día es anónimo: nadie sabrá qué respondiste.',
  'consejo.4': 'Contesta a lo que te cuenta antes de cambiar de tema: se nota que escuchas.',
  'consejo.5': 'El humor ayuda, pero lo que engancha es la curiosidad de verdad.',
  'consejo.6': 'Si la conversación no fluye, pregunta por su plan perfecto de un martes.',
  'consejo.7': 'Tus tres preguntas se leen en el nivel 2: que den algo a lo que responder.',
  'consejo.8': 'Un mensaje largo de vez en cuando dice más que diez de una palabra.',
  'consejo.9': 'Si alguien te hace sentir incómodo, reportar corta la conversación al momento.',
  'chat.errorAbrir': 'No se pudo abrir la conversación.',
  'chat.errorCorazon': 'No se pudo dar el corazón.',
  'chat.errorPedir': 'No se pudo pedir.',
  'chat.errorResponder': 'No se pudo responder.',
  'comun.volver': '‹ Volver',
  'chat.verPerfil': 'Ver perfil ›',
  'chat.conexion': '💖 Conexión',
  'chat.reportar': 'Reportar',
  'chat.hielo': 'Para romper el hielo',
  'chat.pistaCorazon': 'Toca dos veces un mensaje suyo para darle ❤️',
  'chat.cortada': 'Esta conversación está cortada. No os volveremos a emparejar.',
  'chat.cerrada': 'Esta conversación se cerró a las 22:00. Mañana a las 4:00 hay reparto nuevo.',
  'chat.escribe': 'Escribe algo…',
  'comun.edadYDistancia': '{edad} años · a {km} km',
  'comun.sinServidor': 'No se pudo hablar con el servidor.',
  'hoy.miPerfil': 'Mi perfil',
  'hoy.titular': 'Hoy hablas con…',
  'hoy.etiqueta': 'NIVEL 0 · MATCH',
  'hoy.quedan': '⏳ quedan {tiempo}',
  'hoy.distancia': 'a unos {km} km · foto y apodo, todavía no',
  'hoy.unoEnComun': 'Un interés en común contigo',
  'hoy.variosEnComun': '{n} intereses en común contigo',
  'hoy.seguir': 'Seguir hablando',
  'hoy.empezar': 'Toca para empezar a hablar',
  'buscando.titulo': 'Tu emparejamiento de hoy',
  'buscando.cuerpo':
    'Se hace solo, una vez al día y a la misma hora. No eliges tú: se mira que le convenga a los dos.',
  'buscando.cuando': 'Cuándo',
  'buscando.pronto': 'Pronto',
  'buscando.ampliamos':
    'Si llevas días sin encaje, ampliamos la búsqueda poco a poco y te avisamos.',
  'genero.WOMAN': 'Mujer',
  'genero.MAN': 'Hombre',
  'genero.NON_BINARY': 'No binarie',
  'genero.OTHER': 'Otro',
  'busca.WOMAN': 'Mujeres',
  'busca.MAN': 'Hombres',
  'busca.NON_BINARY': 'Personas no binarias',
  'busca.OTHER': 'Otros géneros',
  'intencion.FRIENDSHIP': 'Amistad',
  'intencion.DATING': 'Citas',
  'intencion.RELATIONSHIP': 'Pareja',
  'intencion.CASUAL': 'Algo casual',
  'sociabilidad.1': 'Me cuesta arrancar',
  'sociabilidad.2': 'Más bien reservado',
  'sociabilidad.3': 'Según el día',
  'sociabilidad.4': 'Bastante sociable',
  'sociabilidad.5': 'Hablo con cualquiera',
  'perfil.borrarSiempre': 'Borrar para siempre',
  'perfil.borrarTitulo': '¿Borrar tu cuenta?',
  'perfil.borrarAviso':
    'Se va todo: tu registro, tu foto, tus conversaciones y tus conexiones. También desaparecen para las personas con las que hablaste. No se puede deshacer.',
  'perfil.noSeBorro': 'No se pudo borrar',
  'comun.reintentar': 'Inténtalo de nuevo en un momento.',
  'perfil.edad': 'Edad',
  'perfil.genero': 'Género',
  'perfil.hablarCon': 'Quieres hablar con',
  'perfil.todos': 'Todo el mundo',
  'perfil.edades': 'Edades',
  'perfil.rangoEdad': '{min} – {max} años',
  'perfil.distancia': 'Distancia',
  'perfil.hastaKm': 'Hasta {km} km',
  'perfil.buscas': 'Buscas',
  'perfil.conversacion': 'Conversación',
  'perfil.relacionas': 'Cómo te relacionas',
  'perfil.editar': '✏️ Editar',
  'perfil.basico': 'Lo básico',
  'perfil.idiomas': '🗣️ Idiomas',
  'perfil.intereses': 'Tus intereses',
  'perfil.preguntas': 'Tus tres preguntas',
  'perfil.masDeTi': 'Un poco más de ti',
  'perfil.dedicas': '💼 A qué te dedicas',
  'perfil.deDonde': '🏡 De dónde eres',
  'perfil.ajustes': 'Ajustes',
  'perfil.cambiarRespuestas': 'Cambiar mis respuestas',
  'perfil.cerrarSesion': 'Cerrar sesión',
  'perfil.borrando': 'Borrando…',
  'perfil.borrar': 'Borrar mi cuenta',
  'comoTeVen.titulo': 'Cómo te ven los demás',
  'comoTeVen.pista': 'Toca un nivel para ver qué descubren de ti en él.',
  'comoTeVen.nivel0': '{edad} años, a unos pocos km. Ni tu nombre ni tu foto.',
  'comoTeVen.dosIntereses': 'Solo dos de tus intereses, los que más tengáis en común.',
  'comoTeVen.nivel1': 'Tu apodo, «{apodo}», y todos tus intereses:',
  'comoTeVen.foto': 'Tu foto, si los dos lo pedís',
  'comoTeVen.nivel4':
    '💖 Lo que cada uno quiera compartir. Llega si los dos decís que sí al final del día, y ya no caduca.',
  'comoTeVen.siguiente': '🔒 Siguiente: {desc}',
  'intro.saltar': 'Saltar',
  'intro.1.titulo': 'Habla primero. Ver viene después.',
  'intro.1.frase': 'La foto no es lo primero: se va aclarando conforme la conversación va bien.',
  'intro.2.titulo': 'Una persona al día.',
  'intro.2.frase': 'Cada mañana te toca alguien, y tenéis hasta las 22:00 para hablar.',
  'intro.3.titulo': 'Se desbloquea hablando.',
  'intro.3.frase': 'Cuanto más habláis, más os conocéis. Y la foto, solo si los dos queréis.',
  'intro.4.titulo': 'Al final, decidís los dos.',
  'intro.4.frase': 'Si los dos decís que sí, es una conexión, y ya no caduca.',
  'intro.crearCuenta': 'Crear mi cuenta',
  'intro.siguiente': 'Siguiente',
  'intro.yaTengo': 'Ya tengo cuenta',
  'intro.chat1': '¿Montaña o rocódromo?',
  'intro.chat2': 'Montaña, siempre 🏔️',
  'intro.chat3': '¡Por fin alguien con criterio!',
  'intro.duranteElDia': 'Durante el día',
  'intro.momento1': 'Llega tu persona del día',
  'intro.momento2': 'Habláis a vuestro ritmo',
  'intro.momento3': 'La conversación se cierra',
  'intro.peldano0': 'Edad y dos intereses',
  'intro.peldano1': 'Su apodo, al escribiros',
  'intro.peldano2': 'Sus tres preguntas',
  'intro.peldano3': 'Su foto, si los dos queréis',
  'intro.peldano4': 'Lo que queráis compartir',
  'intro.si': '¿Sí?',
  'login.email': 'Tu email',
  'login.emailAyuda':
    'Te mandamos un código de seis cifras. No hay contraseñas que recordar ni que perder.',
  'login.emailEjemplo': 'tu@email.com',
  'login.enviarCodigo': 'Enviarme el código',
  'login.codigo': 'El código que te hemos enviado',
  'login.codigoAyuda': 'A {email}. Caduca en diez minutos.',
  'login.entrar': 'Entrar',
  'login.otroCodigo': 'Cambiar de email o pedir otro código',
  'login.lema': 'Hablar primero, ver después',
  'comun.sinConexion': 'No se pudo conectar con el servidor.',
  'bloque.quien': 'Quién eres',
  'bloque.busca': 'A quién buscas',
  'bloque.donde': 'Dónde y en qué idioma',
  'bloque.hablas': 'Cómo hablas',
  'bloque.cuentas': 'Qué cuentas de ti',
  'bloque.foto': 'Tu foto',
  'registro.fotoFallo': 'Tu registro está guardado, pero la foto no subió: {motivo}',
  'registro.error': 'No se pudo guardar el registro.',
  'registro.terminar': 'Terminar registro',
  'registro.continuar': 'Continuar',
  'editar.fotoFallo': 'Tus cambios están guardados, pero la foto no subió: {motivo}',
  'editar.error': 'No se pudieron guardar los cambios.',
  'editar.ayuda': 'Toca solo lo que quieras cambiar. Se guarda todo junto al darle abajo.',
  'editar.guardar': 'Guardar cambios',
  'intencion.FRIENDSHIP.pista': 'Gente con quien hablar',
  'intencion.DATING.pista': 'Conocer sin prisa',
  'intencion.RELATIONSHIP.pista': 'Algo que dure',
  'intencion.CASUAL.pista': 'Sin planes a futuro',
  'idioma.es': 'Español',
  'idioma.en': 'Inglés',
  'idioma.ca': 'Catalán',
  'idioma.gl': 'Gallego',
  'idioma.eu': 'Euskera',
  'idioma.fr': 'Francés',
  'idioma.pt': 'Portugués',
  'idioma.it': 'Italiano',
  'idioma.de': 'Alemán',
  'idioma.ar': 'Árabe',
  'idioma.ro': 'Rumano',
  'idioma.nl': 'Neerlandés',
  'idioma.pl': 'Polaco',
  'idioma.ru': 'Ruso',
  'idioma.uk': 'Ucraniano',
  'idioma.zh': 'Chino',
  'idioma.ja': 'Japonés',
  'idioma.ko': 'Coreano',
  'idioma.hi': 'Hindi',
  'idioma.ur': 'Urdu',
  'idioma.bn': 'Bengalí',
  'idioma.tr': 'Turco',
  'idioma.el': 'Griego',
  'idioma.sv': 'Sueco',
  'idioma.no': 'Noruego',
  'idioma.da': 'Danés',
  'idioma.fi': 'Finés',
  'idioma.cs': 'Checo',
  'idioma.hu': 'Húngaro',
  'idioma.he': 'Hebreo',
  'nivelIdioma.BASIC': 'Lo chapurreo',
  'nivelIdioma.INTERMEDIATE': 'Me defiendo',
  'nivelIdioma.NATIVE': 'Como en casa',
  'generoDetalle.0': 'Mujer',
  'generoDetalle.1': 'Hombre',
  'generoDetalle.2': 'Mujer trans',
  'generoDetalle.3': 'Hombre trans',
  'generoDetalle.4': 'No binarie',
  'generoDetalle.5': 'Género fluido',
  'generoDetalle.6': 'Agénero',
  'generoDetalle.7': 'Bigénero',
  'generoDetalle.8': 'Queer',
  'generoDetalle.9': 'Intergénero',
  'generoDetalle.10': 'Cuestionándomelo',
  'generoDetalle.11': 'Prefiero no decirlo',
  'pregunta.last-hooked.ejemplo': 'Ej.: un documental sobre pulpos, me lo vi dos veces',
  'pregunta.always-ask.ejemplo': 'Ej.: ¿cuál es tu desayuno ideal?',
  'pregunta.weird-habit.ejemplo': 'Ej.: le pongo nombre a todas mis plantas',
  'pregunta.makes-me-laugh.ejemplo': 'Ej.: los vídeos de gatos que se caen',
  'pregunta.perfect-tuesday.ejemplo': 'Ej.: café, paseo por la playa y una serie',
  'pregunta.learned-late.ejemplo': 'Ej.: a nadar, con 25 años',
  'pregunta.hill-to-die-on.ejemplo': 'Ej.: la tortilla, con cebolla',
  'pregunta.surprisingly-good-at.ejemplo': 'Ej.: aparcar a la primera',
  'pregunta.always-return.ejemplo': 'Ej.: un bar de mi barrio con las mejores bravas',
  'pregunta.changed-my-mind.ejemplo': 'Ej.: antes odiaba correr',
  'pregunta.too-much-internet.ejemplo': 'Ej.: los vídeos de diez segundos',
  'pregunta.want-to-try.ejemplo': 'Ej.: hacer surf de una vez',
  'pregunta.worst-recommendation.ejemplo': 'Ej.: una peli que nadie aguantó entera',
  'pregunta.gives-me-away.ejemplo': 'Ej.: mi risa, se oye desde la otra punta',
  'pregunta.not-in-my-interests.ejemplo': 'Ej.: colecciono postales antiguas',
  'apodo.titulo': '¿Cómo quieres que te llamen?',
  'apodo.ayuda':
    'Aparece en el nivel 1, en cuanto escribáis los dos. Tu nombre real no hace falta.',
  'apodo.placeholder': 'Tu apodo',
  'nacimiento.titulo': 'Tu fecha de nacimiento',
  'nacimiento.ayuda':
    'Solo para mayores de 18. Antes de la beta verificaremos la edad de verdad, no con una casilla.',
  'genero.titulo': 'Tu género',
  'genero.ayuda':
    'De estos cuatro sale el emparejamiento, y por eso son cuatro. En el nivel 0 solo se ve tu edad, dos intereses y tu zona.',
  'generoDetalle.titulo': '¿Y cómo lo dices tú?',
  'generoDetalle.ayuda':
    'Opcional. Esto se lee en el nivel 3 y no se usa para emparejar, así que puedes ser todo lo preciso que quieras.',
  'generoDetalle.placeholder': 'O escríbelo como quieras',
  'busco.titulo': '¿Con quién quieres hablar?',
  'busco.ayuda': 'Puedes marcar varias. Solo emparejamos si encaja por los dos lados.',
  'busco.todosDetalle': 'Marca las cuatro de arriba',
  'rango.titulo': 'Edad y distancia',
  'rango.ayuda': 'Si llevas días esperando, ampliamos esto poco a poco y te avisamos.',
  'ubicacion.titulo': '¿Dónde estás?',
  'ubicacion.ayuda':
    'Se pide una vez y se guarda redondeada a más de un kilómetro. No se sigue tu recorrido.',
  'ubicacion.usar': 'Usar mi ubicación',
  'idiomas.titulo': '¿En qué idiomas hablas?',
  'idiomas.ayuda':
    'Aquí todo pasa por escribir, así que hace falta un idioma en común. Di también cómo lo hablas: si lo marcas flojo, no te pondremos con alguien con quien solo compartes ese idioma.',
  'rasgos.ayuda': 'Sin respuestas buenas ni malas: sirve para no juntar ritmos incompatibles.',
  'conversacion.titulo': '¿Qué conversación te gusta?',
  'conversacion.ayuda': 'De aquí sale la pregunta con la que arranca tu primer chat.',
  'intencion.titulo': '¿Qué buscas ahora?',
  'intencion.ayuda': 'Elige lo que más pese hoy. Se puede cambiar cuando quieras.',
  'intereses.buscar': 'Buscar',
  'preguntas.ayuda':
    'Elige tres y termina la frase. Es lo que la otra persona leerá en el nivel 2, y le da algo a lo que responder.',
  'masDeTi.dedicasEjemplo': 'Ej.: enfermera, estudio diseño…',
  'masDeTi.deDondeEjemplo': 'Ej.: Girona, aunque vivo en Barcelona',
  'fotoPropia.titulo': 'Una foto tuya',
  'rango.edad': '🎂 Edad de las personas',
  'rango.distancia': '📍 Distancia',
  'ubicacion.tomada': 'Ubicación tomada',
  'intereses.tuyos': 'Los tuyos',
  'intereses.nada': 'Nada con ese nombre.',
  'preguntas.cambiar': 'Cambiar ›',
  'preguntas.verMuestra': '👀 Así lo verá la otra persona',
  'preguntas.elige': 'Elige una pregunta',
  'preguntas.sorpresa': '🎲 Sorpréndeme',
  'preguntas.enSuPantalla': 'En su pantalla, en el nivel 2',
  'masDeTi.opcional': 'Opcional',
  'masDeTi.nivel3': '🔒 Se ve a partir del nivel 3',
  'fotoPropia.tocar': 'Tocar para elegir',
  'fotoPropia.otra': 'Elegir otra',
  'fotoPropia.queHacemos': 'Qué hacemos con ella',
  'nacimiento.vacio': 'Toca las casillas y escribe día, mes y año',
  'nacimiento.noExiste': 'Esa fecha no existe, revísala',
  'nacimiento.menor': 'Olimpus es solo para mayores de 18',
  'nacimiento.tienes': 'Tienes {edad} años',
  'rango.deA': 'De {min} a {max} años',
  'ubicacion.sinPermiso':
    'Sin ubicación no podemos calcular la distancia. Puedes darla en Ajustes.',
  'ubicacion.sinGps': 'No se pudo leer la ubicación. Comprueba que el GPS está encendido.',
  'ubicacion.error': 'No se pudo leer la ubicación.',
  'ubicacion.nota':
    'Guardada con poca precisión a propósito: sirve para la distancia, no para encontrarte.',
  'intereses.titulo': 'Entre {min} y {max} intereses',
  'pregunta.ejemploGenerico': 'Termina la frase a tu manera',
  'fotoPropia.errorGaleria': 'No se pudo abrir la galería.',
  'fotoPropia.nota':
    'Se reduce en tu móvil antes de enviarla, y al reescribirla se pierden los datos ocultos que llevan las fotos, incluido el lugar donde se hizo. En el servidor no hay ningún enlace público: cada vez que alguien la pide, se comprueba si tiene derecho a verla.',
  'rango.barrio': '🏘️ Tu barrio y alrededores',
  'rango.ciudad': '🏙️ Tu ciudad',
  'rango.zona': '🚗 Tu zona, a un rato en coche',
  'rango.provincia': '🗺️ Toda tu provincia y más',
  'ubicacion.tomando': 'Tomando…',
  'ubicacion.otraVez': 'Volver a tomarla',
  'intereses.llevas': 'Llevas {n}. De aquí sale la primera pregunta de cada conversación.',
  'intereses.elegidos': '{n} elegidos. Cuanto más raro, más dice de ti.',
  'preguntas.hueco0': 'Elige tu primera pregunta',
  'preguntas.hueco1': 'Elige tu segunda pregunta',
  'preguntas.hueco2': 'Elige tu tercera pregunta',
  'fotoPropia.yaTienes': 'Ya tienes una guardada. Tócala solo si quieres cambiarla.',
  'fotoPropia.ayuda':
    'Nadie la ve al emparejar. Aparece en el nivel 3, y solo si los dos habéis dicho que queréis veros.',
  'rasgo.titulo.largo': 'Al escribir',
  'rasgo.titulo.ritmo': 'Mi ritmo',
  'rasgo.titulo.rol': 'En una charla',
  'rasgo.largos': 'Mensajes largos',
  'rasgo.depende': 'Depende',
  'rasgo.cortos': 'Cortos y seguidos',
  'rasgo.cuandoPuedo': 'Cuando puedo',
  'rasgo.alMomento': 'Contesto al momento',
  'rasgo.escucho': 'Escucho más',
  'rasgo.pregunto': 'Pregunto mucho',
  'conversacion.A fondo': 'A fondo',
  'conversacion.Ligera y con humor': 'Ligera y con humor',
  'conversacion.Curiosa': 'Curiosa',
  'conversacion.Pr\u00e1ctica': 'Práctica',
  'conversacion.pista.A fondo': 'Pocos temas, bien tratados',
  'conversacion.pista.Ligera y con humor': 'Sin ponerse intenso',
  'conversacion.pista.Curiosa': 'Preguntas raras, hipótesis',
  'conversacion.pista.Pr\u00e1ctica': 'Planes, ciudad, qué hacer',
  'comun.servidorRespondio': 'El servidor respondió {estado}',
  'fotoPropia.errorSubir': 'No se pudo subir la foto.',
  'fotoPropia.sinPermiso': 'Sin permiso no podemos abrir tus fotos. Puedes dárnoslo en Ajustes.',
  'idiomaApp.titulo': 'Idioma de la app',
  'idiomaApp.ayuda': 'Los mensajes y perfiles de otras personas se quedan como los escribieron.',
  'rango.zonaNota': 'Tu zona nunca se muestra exacta: la otra persona lee «a 3 km de ti».',
  'masDeTi.nota': 'No se usan para emparejar: solo para que te conozcan.',
  'subida.titulo': '¡Nivel {nivel}!',
  'subida.desbloqueado': 'Ya puedes ver: {desc}',
};

export type Clave = keyof typeof es;
